global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "host"
    static_configs:
      - targets: ["host.docker.internal:9100"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "snmp-exporter"
    static_configs:
      - targets: ["snmp-exporter:9116"]